name: Gated-OSX
on:
 push:
   branches:
    - 'releases/**'
    - dev
 pull_request:
   branches:
    - 'releases/**'
    - dev
jobs:
  build_osx:
    runs-on: macOS-latest
    strategy:
      fail-fast: false # Disable the auto cancelling of all in-progress and queued jobs in the matrix if any job in the matrix fails.
      matrix:
        dotnet-version: [ '9.0.x', '8.0.x', '6.0.x' ]
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
          - 'src/**'
          - 'test/**'
          - 'build/**'
          - 'samples/**'
          - '*.cmd'
          - '*.ps1'
          - '**.props'
          - '**.csproj'
          - '**.targets'
          - '*.sh'
          - '*.sln'
    - name: Update SubModules
      if: steps.filter.outputs.src == 'true'
      run: git submodule update --init --recursive
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Display dotnet version
      run: dotnet --version
    - name: Build with dotnet
      run: |
        dotnet sln AzureSignalR.sln remove test/Microsoft.Azure.SignalR.Protocols.Tests/Microsoft.Azure.SignalR.Protocols.Tests.csproj
        dotnet sln AzureSignalR.sln remove test/Microsoft.Azure.SignalR.Emulator.Tests/Microsoft.Azure.SignalR.Emulator.Tests.csproj
        dotnet sln AzureSignalR.sln remove test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj
        dotnet sln AzureSignalR.sln remove test/Microsoft.Azure.SignalR.Serverless.Protocols.Tests/Microsoft.Azure.SignalR.Serverless.Protocols.Tests.csproj
        dotnet sln AzureSignalR.sln remove test/Microsoft.Azure.SignalR.IntegrationTests/Microsoft.Azure.SignalR.IntegrationTests.csproj
        dotnet build AzureSignalR.sln /p:DisableNet461Tests=true
      if: steps.filter.outputs.src == 'true'
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-ubuntu-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-ubuntu-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}